// Generated by CoffeeScript 1.4.0
(function() {
  var Amostra, Lote;

  Amostra = (function() {

    function Amostra(exame, valRef) {
      var dataCriacao;
      this.exame = exame;
      this.valRef = valRef;
      dataCriacao = Date.now();
    }

    return Amostra;

  })();

  Lote = (function() {

    Lote.emProcesso = {};

    Lote.processado = {};

    function Lote() {
      this.status = 'CRIADO';
    }

    Lote.prototype.addAmostra = function(amostra) {
      emProcesso.add(amostra);
      if (this.status === 'CRIADO') {
        this.status = 'EMPROCESSO';
      }
      return $.promise().done().error();
    };

    return Lote;

  })();

}).call(this);
