// Generated by CoffeeScript 1.9.2
(function() {
  var Amostra, Lote, alerta;

  Amostra = (function() {
    function Amostra(exame, valRef) {
      var dataCriacao;
      this.exame = exame;
      this.valRef = valRef;
      dataCriacao = Date.now();
    }

    return Amostra;

  })();

  Lote = (function() {
    Lote.emProcesso = {};

    Lote.processado = {};

    function Lote() {
      this.status = 'CRIADO';
    }

    Lote.prototype.addAmostra = function(amostra) {
      emProcesso.add(amostra);
      if (this.status === 'CRIADO') {
        return this.status = 'EMPROCESSO';
      }
    };

    return Lote;

  })();

  alerta = function(v) {
    return alert(v);
  };

  $(document).ready(function() {
    $("#btnTeste").on("click", $.proxy(alerta, this, "abacate"));
    return $("#btnAdAmotra").click(alerta);
  });

}).call(this);

//# sourceMappingURL=main.js.map
